"""add reopen_count to tasks"""

revision = '3fadc5024285'
down_revision = 'af4b79318645'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # set giá trị mặc định cho các dòng cũ
    op.execute(
        "UPDATE tasks SET reopen_count = 0 WHERE reopen_count IS NULL"
    )

    # đổi sang NOT NULL
    op.alter_column(
        'tasks',
        'reopen_count',
        existing_type=sa.INTEGER(),
        nullable=False,
        server_default="0"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'reopen_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
