"""Update activity logs schema"""

revision = 'a0e272b985c3'
down_revision = 'd7b098d8d51c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('action_type', sa.String(length=50), nullable=False))
    op.add_column('activity_logs', sa.Column('entity_type', sa.String(length=50), nullable=False))
    op.add_column('activity_logs', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_activity_logs_action_type'), 'activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.drop_constraint('activity_logs_user_id_fkey', 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'users', ['user_id'], ['id'])
    op.drop_column('activity_logs', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key('activity_logs_user_id_fkey', 'activity_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action_type'), table_name='activity_logs')
    op.drop_column('activity_logs', 'entity_id')
    op.drop_column('activity_logs', 'entity_type')
    op.drop_column('activity_logs', 'action_type')
    # ### end Alembic commands ###
