"""add missing project task fields"""

revision = 'a725f9a30cd1'
down_revision = '20260531_003'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'severity',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'info'::character varying"))
    op.alter_column('notifications', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('notifications', 'is_ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_pal_changed_by', table_name='project_audit_logs')
    op.drop_index('ix_pal_project_id', table_name='project_audit_logs')
    op.create_index(op.f('ix_project_audit_logs_changed_by'), 'project_audit_logs', ['changed_by'], unique=False)
    op.create_index(op.f('ix_project_audit_logs_project_id'), 'project_audit_logs', ['project_id'], unique=False)
    op.drop_index('ix_milestones_project_id', table_name='project_milestones')
    op.create_index(op.f('ix_project_milestones_project_id'), 'project_milestones', ['project_id'], unique=False)
    op.drop_index('ix_psh_project_id', table_name='project_status_history')
    op.create_index(op.f('ix_project_status_history_project_id'), 'project_status_history', ['project_id'], unique=False)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_project_status_history_project_id'), table_name='project_status_history')
    op.create_index('ix_psh_project_id', 'project_status_history', ['project_id'], unique=False)
    op.drop_index(op.f('ix_project_milestones_project_id'), table_name='project_milestones')
    op.create_index('ix_milestones_project_id', 'project_milestones', ['project_id'], unique=False)
    op.drop_index(op.f('ix_project_audit_logs_project_id'), table_name='project_audit_logs')
    op.drop_index(op.f('ix_project_audit_logs_changed_by'), table_name='project_audit_logs')
    op.create_index('ix_pal_project_id', 'project_audit_logs', ['project_id'], unique=False)
    op.create_index('ix_pal_changed_by', 'project_audit_logs', ['changed_by'], unique=False)
    op.alter_column('notifications', 'is_ai_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'system'::character varying"))
    op.alter_column('notifications', 'severity',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'info'::character varying"))
    # ### end Alembic commands ###
