"""Create KPI tables"""

revision = 'af4b79318645'
down_revision = '87617b674ca9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_kpi_rules_id'), 'kpi_rules', ['id'], unique=False)
    op.create_table('kpi_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=True),
    sa.Column('period_key', sa.String(length=20), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('tasks_overdue', sa.Integer(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_snapshots_id'), 'kpi_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_snapshots_period_key'), 'kpi_snapshots', ['period_key'], unique=False)
    op.create_index(op.f('ix_kpi_snapshots_user_id'), 'kpi_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kpi_snapshots_user_id'), table_name='kpi_snapshots')
    op.drop_index(op.f('ix_kpi_snapshots_period_key'), table_name='kpi_snapshots')
    op.drop_index(op.f('ix_kpi_snapshots_id'), table_name='kpi_snapshots')
    op.drop_table('kpi_snapshots')
    op.drop_index(op.f('ix_kpi_rules_id'), table_name='kpi_rules')
    op.drop_table('kpi_rules')
    # ### end Alembic commands ###
